chore: workflows

diff --git a/.github/workflows/run_example.yaml b/.github/workflows/run_example.yaml
--- a/.github/workflows/run_example.yaml
+++ b/.github/workflows/run_example.yaml
@@ -10,26 +10,30 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
-      
       - name: setup go
         uses: actions/setup-go@v4
         with:
           go-version: '1.22.x'
-
       - name: run example
         run: |
           cd examples/
           go run main.go
-          
+      - name: check generated files
+        run: |
+          if [ -f examples.png ]; then
+            echo "File exists"
+          else
+            echo "File not found"
+            exit 1
+          fi
       - name: auto commit
         uses: stefanzweifel/git-auto-commit-action@v5
         with:
-          commit_message: "[AUTO]"
+          commit_message: "[AUTO] Generated examples.png"
           branch: master
           commit_options: '--no-verify --signoff'
           repository: .
-          skip_dirty_check: true    
-          skip_fetch: true 
+          skip_dirty_check: false
+          skip_fetch: false
           skip_checkout: true
           disable_globbing: true
-          create_branch: true
